formatter: "markdown" # this is required

output:
  file: ""
  mode: inject
  template: |-
    <!-- BEGINNING OF PRE-COMMIT-TERRAFORM DOCS HOOK -->
    {{ .Content }}
    <!-- END OF PRE-COMMIT-TERRAFORM DOCS HOOK -->
sort:
  enabled: true
  by: name
settings:
  lockfile: false
